spring :
  data :
    mongodb :
      uri : link
      database : journaldb
      auto-index-creation : true

logging:
  level:
    com:
      example:
        Journaldemo: TRACE


server:
  port : 8080
