#spring.data.mongodb.uri=mongodb+srv://shivamvarshney3012:Shivam1506@cluster0.oplfufb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database = journaldb
#spring.data.mongodb.auto-index-creation=true
#
#server.port = 8080