spring :
  data :
    mongodb :
      uri : mongodb+srv://shivamvarshney3012:Shivam1506@cluster0.oplfufb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database : journaldb
      auto-index-creation : true

logging:
  level:
    com:
      example:
        Journaldemo: TRACE


server:
  port : 8080
